# Generated by Django 4.2.5 on 2024-03-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('idd', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
