# Generated by Django 4.2.5 on 2024-03-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idd',
            new_name='id',
        ),
    ]
