# Generated by Django 4.2.5 on 2024-03-28 19:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_delete_user_delete_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bassword', models.CharField(max_length=20, validators=[blog.models.validate_min_length])),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
