# Generated by Django 4.2.5 on 2024-03-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField(default='Your default value')),
                ('nanasha', models.FloatField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
