# Generated by Django 4.2.5 on 2024-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='nanasha',
            field=models.FloatField(null=True),
        ),
    ]
