# Generated by Django 4.2.5 on 2024-03-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bill',
        ),
    ]
