# Generated by Django 4.2.5 on 2024-03-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='expenses',
        ),
        migrations.DeleteModel(
            name='person',
        ),
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
