# Generated by Django 4.2.5 on 2024-03-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'user_id')},
        ),
    ]
